export default {
    animating: true,
    action: "stand1",
    frame: 0,
    mercEars: false,
    illiumEars: false,
    highFloraEars: false,
    zoom: 2,
    name: "",
    flipX: false,
    includeBackground: true,
    selectedItems: {
        Body: {
            name: "Body",
            noIcon: true,
            id: 2015,
            region: "KMS",
            version: "360",
            typeInfo: {
                category: "Character",
                highItemId: 2999,
                lowItemId: 2010,
                overallCategory: "Character",
                subCategory: "Body",
            },
        },
        Head: {
            name: "Head",
            noIcon: true,
            id: 12015,
            region: "KMS",
            version: "360",
            typeInfo: {
                category: "Character",
                highItemId: 12999,
                lowItemId: 12000,
                overallCategory: "Character",
                subCategory: "Head",
            },
        },
        Hair: {
            requiredJobs: ["Beginner"],
            isCash: true,
            requiredGender: 2,
            name: "검은색 데이즈 헤어",
            desc: "",
            id: "61370",
            typeInfo: {
                overallCategory: "Equip",
                category: "Character",
                subCategory: "Hair",
                lowItemId: 30000,
                highItemId: 49999,
            },
            region: "KMS",
            version: "360",
        },
        Face: {
            requiredJobs: ["Beginner"],
            isCash: true,
            requiredGender: 2,
            name: "나도코있다 얼굴",
            desc: "",
            id: "26079",
            typeInfo: {
                overallCategory: "Equip",
                category: "Character",
                subCategory: "Face",
                lowItemId: 20000,
                highItemId: 29999,
            },
            region: "KMS",
            version: "360",
        },
        EyeDecoration: {
            requiredJobs: ["Beginner"],
            requiredLevel: 0,
            isCash: true,
            requiredGender: 0,
            name: "동글이 안경",
            desc: "",
            id: "1022285",
            typeInfo: {
                overallCategory: "Equip",
                category: "Accessory",
                subCategory: "Eye Decoration",
                lowItemId: 1020000,
                highItemId: 1030000,
            },
            region: "KMS",
            version: "360",
        },
        Overall: {
            requiredJobs: ["Warrior"],
            requiredLevel: 35,
            isCash: false,
            requiredGender: 0,
            name: "여신의 가호 한벌옷",
            desc: "",
            id: "1053828",
            typeInfo: {
                overallCategory: "Equip",
                category: "Armor",
                subCategory: "Overall",
                lowItemId: 1050000,
                highItemId: 1060000,
            },
            region: "KMS",
            version: "360",
        },
        FaceAccessory: {
            requiredJobs: ["Beginner"],
            requiredLevel: 0,
            isCash: true,
            requiredGender: 0,
            name: "아련한 메이크업",
            desc: "",
            id: "1011006",
            typeInfo: {
                overallCategory: "Equip",
                category: "Accessory",
                subCategory: "Face Accessory",
                lowItemId: 1010000,
                highItemId: 1020000,
            },
            region: "KMS",
            version: "360",
        },
    },
};
